name: Build and deploy documentation

on:
  push:
    branches: [ main ]

env:
  WORKFLOWS_DIR: .github/workflows

jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build lambeq
      run: pip install .
    - name: Install documentation dependencies
      run: |
        sudo apt-get install pandoc
        pip install -r docs/requirements.txt
    - name: Build documentation
      run: ${{ env.WORKFLOWS_DIR }}/build-docs
    - name: Deploy documentation
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: docs
        FOLDER: docs/_build/html/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAR_GLOBS_FILE: ${{ env.WORKFLOWS_DIR }}/clear-target-files
